[package]
name = "encryption_with_chunk"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
aes = "0.7.5"
block-modes = "0.8"
cipher = { version = "0.4.4", features = ["block-padding"] }
hmac = "0.12"
sha2 = "0.10"
rand = "0.8"

